Repository Deliver-IF/App-Deliver-IF, pull requests merged in 2023-03, with the labels that each got.

#13 Don't register intersection reachable in double
  src/main/java/com/deliverif/app/models/map/Segment.java
Labels: bug

#39 Change number of courier
  src/main/java/com/deliverif/app/controller/MainController.java
  src/main/java/com/deliverif/app/controller/MapController.java
  src/main/java/com/deliverif/app/model/CityMap.java
  src/main/java/com/deliverif/app/model/Courier.java
  src/main/java/com/deliverif/app/model/DeliveryTour.java
  src/main/java/com/deliverif/app/services/DeliveryService.java
  src/main/resources/com/deliverif/app/view/main.fxml
  src/test/java/com/deliverif/app/algorithm/NaiveAlgorithmTest.java
  src/test/java/com/deliverif/app/services/DeliveryServiceTest.java
  src/test/resources/com/deliverif/app/services/DeliveryService/expected/saveDeliveriesToFile.xml
  src/test/resources/com/deliverif/app/services/DeliveryService/input/loadDeliveriesFromFile.xml
Labels: bug, enhancement

#47 26 nothing happen when you try to load a map when one is already load + Redraw map on window resize implementation
  src/main/java/com/deliverif/app/Main.java
  src/main/java/com/deliverif/app/controller/MainController.java
  src/main/java/com/deliverif/app/controller/MapController.java
  src/main/java/com/deliverif/app/services/DeliveryService.java
Labels: bug, enhancement

#69 67 warning on load new map if tour isnt save
  src/main/java/com/deliverif/app/controller/MainController.java
Labels: enhancement
